### ISSUE TITLE
User permissions in docker container

### ISSUE THREAD

**Issue by jtomasrl** [eclipse/mosquitto#1260]
Im running version 1.6.2 on a docker container (RPI3). After starting the container I'm getting some permission errors.

The first one is related to the log file, not surprised after some google:
`1557112636: Error: Unable to open log file /appdata/mosquitto/log/mosquitto.log for writing.`

After giving up on logging and removing it completely, Im getting this now:
```
1557112642: mosquitto version 1.6.2 starting
1557112642: Config loaded from /mosquitto/config/mosquitto.conf.
1557112642: Error: Unable to open pwfile "/appdata/mosquitto/data/passwd".
1557112642: Error opening password file "/appdata/mosquitto/data/passwd".
```
How is the config file loaded, but the other files don't?

This is my current setup: first of all, user id and groups

```
$ whoami
jtomasrl

$ id jtomasrl
uid=1000(jtomasrl) gid=1000(jtomasrl) groups=1000(jtomasrl),27(sudo),996(docker)
```

docker-compose.yml

```
version: '2.1'

services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    user: 1000:1000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /appdata/mosquitto/config:/mosquitto/config:ro
      - /appdata/mosquitto/data:/mosquitto/data
    ports:
      - 1883:1883
    restart: unless-stopped
    networks:
      macvlan_network:
        ipv4_address: x.x.x.x
```

This is my folder structure and permissions `/appdata/mosquitto/`

```
$ ls -l
drwxr-xr-x 2 jtomasrl jtomasrl 4096 May  5 23:13 config
drwxr-xr-x 2 jtomasrl jtomasrl 4096 May  5 23:01 data
drwxr-xr-x 2 jtomasrl jtomasrl 4096 May  5 18:08 log
```

and finally my mosquitto.conf

```
persistence true
persistence_location /appdata/mosquitto/data/

allow_anonymous false
password_file /appdata/mosquitto/data/passwd

# Port to use for the default listener.
port 1883

log_dest stdout
```

Bonus: I also tried all this creating a user called `mosquitto` and changing the corresponding files and permissions.

```
$ id mosquitto
uid=1883(mosquitto) gid=1883(mosquitto) groups=1883(mosquitto),996(docker)
```

I also tried adding some environment variables on the docker-compose.yml
```
    environment:
      - PUID=1000
      - PGID=1000
```

Something is really broken with this container, I'm not having problem with any other.
