### ISSUE TITLE
Unable to save in-memory data in docker container: Invalid Argument

### ISSUE THREAD

**Issue by wizcas** [eclipse/mosquitto#1558]
I'm running mosquitto in a docker container. Log files can be stored without problems, but errors occur when trying to save in-memory data on exiting. Below are the logs:

```
2020-01-13T08:02:26: mosquitto version 1.6.8 starting
2020-01-13T08:02:26: Config loaded from /mosquitto/config/mosquitto.conf.
2020-01-13T08:02:26: Opening ipv4 listen socket on port 1883.
2020-01-13T08:02:26: Opening ipv6 listen socket on port 1883.
^C2020-01-13T08:02:28: mosquitto version 1.6.8 terminating
2020-01-13T08:02:28: Saving in-memory database to mosquitto.db.
2020-01-13T08:02:28: Error saving in-memory database, unable to open mosquitto.db.new for writing.
2020-01-13T08:02:28: Error: Invalid argument.
```

Note the last line which says: **Invalid argument**.

I'm not sure what it means nor how to solve it. Tried to change persistence directory, filename and `chown`. Nothing works. It doesn't even work without any binding volume. I don't think it's a permission issue.

Can anyone please help me? Thanks!

**Comment by daenney** [comment]
How are you running the container, as in what's the full `docker` command you use to start it?

**Comment by wizcas** [comment]
@daenney The problem exists by both `docker run` and `docker compose`. The docker compose config is like:

```yaml
# docker-compose.yml
version: '3.7'
services:
  broker:
    image: eclipse-mosquitto
    container_name: mqtt.svc
    restart: always
    ports:
      - "1883:1883"
      - "1884:80"
    volumes:
      - type: bind
        source: ./mosquitto.conf
        target: /mosquitto/config/mosquitto.conf
      - type: bind
        source: ./pwd
        target: /mosquitto/pwd
      - type: bind
        source: ./acl
        target: /mosquitto/acl
      - type: bind
        source: ./data/
        target: /var/lib/mosquitto/
      - type: bind
        source: ./log
        target: /mosquitto/log
      - type: bind
        source: ./storage
        target: /mosquitto/storage%
```

> How are you running the container, as in what's the full `docker` command you use to start it?
