### ISSUE TITLE
Missing libraries  --> symbol not found errors

### ISSUE THREAD

**Issue by gregbert42** [eclipse/mosquitto#1784]
Error loading shared library libssl.so.48: No such file or directory (needed by /usr/sbin/mosquitto)
Error loading shared library libcrypto.so.46: No such file or directory (needed by /usr/sbin/mosquitto)

full error logs from docker: http://sprunge.us/qQBtAp

docker-compose:

```
version: "2.2"
services:
  mosquitto:
    container_name: mosquitto
    restart: unless-stopped
    image: eclipse-mosquitto
    networks:
      - default
    environment:
      - TZ="Europe/Zurich"
      - PGID=1002 -e PUID=1002
      - MQTTHOSTNAME="xyz.com"
    ports:
      - 8080:8080
      - 1883:1883
      - 8883:8883
    volumes:
      - /home/xyz/conf/mosquitto_and_owntracks/mosquitto-data:/mosquitto/data
      - /home/xyz/conf/mosquitto_and_owntracks/mosquitto-logs:/mosquitto/logs
      - /home/xyz/conf/mosquitto_and_owntracks/mosquitto-conf:/mosquitto/config
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

```
