### ISSUE TITLE
V1.6.12 Windows, When the log is enabled, the broker stops working

### ISSUE THREAD

**Issue by ArielGuille** [eclipse/mosquitto#1807]
The installation of version 1.6.12 for windows works correctly (x32 and x64) as well as manual execution or service. When I enable the log with "log_dest file C: \ temp \ mosquitto.log" the broker stops working. I install version V1.6.10 and the log works ok

**Comment by alexnowak** [comment]
I have the same problem on Windows 10 with 1.6.12. 
Only active settings in mosquitto.conf:

log_dest file C:\\Temp\\mosquitto.log
log_type all

(also tried c:/Temp/mosquitto.log and C:\\Temp\\mosquitto.log, same result)

Starting the broker from the command line with 

mosquitto -c "C:\Program Files\mosquitto\mosquitto.conf"

It seemed to crash the broker. The command returned with no message.  The directory c:\temp exists and is writeable.
If log_dest is commented out, it works just fine.  Messages are visible from the command line.

**Comment by Jleagle** [comment]
I just got this, using the following on Debian:

```
  mosquitto:
    container_name: mosquitto
    hostname: mosquitto
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    volumes:
      - ${HOME}/Mosquitto/Log/mosquitto.log:/mosquitto/log/mosquitto.log
      - ${HOME}/Mosquitto/Data:/mosquitto/data
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
```

```
persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log
listener 1883 0.0.0.0
allow_anonymous true
```

Container starts, creates log file, but no logs. I can fix it by removing the `log_dest` line.
