### ISSUE TITLE
Directory log problem.

### ISSUE THREAD

**Issue by sirsiegfrieds** [eclipse/mosquitto#1838]
Hey there,

i'm using mosquitto for a couple of day. It was running properly since i have done a docker-compose pull.

Now it's looks like he doesn't find, or have a right problem to accès to mosquitto.log

My compose is :
``` 
################
####MOSQUITTO###
################

  mqtt:
    container_name: mosquitto
    hostname: mosquitto
    image: eclipse-mosquitto:latest
    restart: always
    volumes:
      - /opt/docker/mosquitto/config:/mosquitto/config
      - /opt/docker/mosquitto/data:/moquitto/data
      - /opt/docker/mosquitto/log:/mosquitto/log
    expose:
      - 1883
      - 9001
    ports:
      - 1883:1883  
      - 9001:9001
    networks:
      - default
```
Folder right : 
drwxr-xr-x 2 1883 1883 4096 oct.   7 22:47 /opt/docker/mosquitto/log

And errors in portainer log:

1602096188: Error: Unable to open log file /opt/docker/mosquitto/log/mosquitto.log for writing.
1602097989: Error: No such file or directory.

I'm not a real pro in using docker, so if one of us can help in found the problem, it would be great

( Sorry for my poo english, i'm french )
