### ISSUE TITLE
Error saving in-memory database

### ISSUE THREAD

**Issue by Altycoder** [eclipse/mosquitto#1909]
I have a problem similar to #1078 but as that's a 2 year old thread that's closed I've opened new one.

I've tried all the advice given in that thread but still get the error:

```
1606229875: Error saving in-memory database, unable to open /mnt/btrfs_raid/docker/mosquitto/data/mosquitto.db.new for writing.,
1606229875: Error: No such file or directory.,
1606229875: Saving in-memory database to /mnt/btrfs_raid/docker/mosquitto/data/mosquitto.db.
```

Things I've tried:

- whole path from /mnt down to final directory are all 0777 permissions
- all my other docker containers read/write to /mnt/btrfs_raid/docker/... no problem
- run the container with uid and gid of 1000/1001 which all my other docker containers run as
- run the container without specifying a uid or gid and give the mosquitto directory and sub-folders user/group ownership of 1883
- specify user: "1000:1001"

Nothing is working, what else can I try?  my docker-compose:

```
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    restart: always
    user: "1000:1001"
    environment:
    - TZ=Europe/London
#    - UID=1000
#    - GID=1001
#    - UMASK=002    
    volumes:
      - /mnt/btrfs_raid/docker/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /mnt/btrfs_raid/docker/mosquitto/data:/mosquitto/data
      - /mnt/btrfs_raid/docker/mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001
```
