### ISSUE TITLE
Homie device OTA problem with release 2.0.0

### ISSUE THREAD

**Issue by labodj** [eclipse/mosquitto#1929]
Hi,
I'm experiencing a problem to perform OTA update to esp32 devices running [homie-esp8266](https://github.com/homieiot/homie-esp8266) firmware, (I use [my fork](https://github.com/labodj/homie-esp8266) of that firmware/library).

To perform the OTA update I use a python script, you can find it [here](https://github.com/labodj/homie-esp8266/tree/develop/scripts/ota_updater).

The problem is that esp32 devices are not receiving all packets (maybe they recieve only the first one, I don't know) and it started since 2.0.0 release, it work wirthout any effort using 1.6.12 with the same config.

My setup:
- Mosquitto broker running on docker, managed via portainer, host network, Raspberry Pi 4 4GB, Raspberry Pi OS latest version, SSD boot
- 13 MQTT clients (every device use the same user: homie)
- No SSL

Docker compose:

```yaml
version: '2.4'
services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2.0.0
    restart: always
    network_mode: 'host'
    volumes:
      # Data
      - '/home/pi/docker/mosquitto/config:/mosquitto/config'
      - '/home/pi/docker/mosquitto/data:/mosquitto/data'
      - '/home/pi/docker/mosquitto/log:/mosquitto/log'
      # Correct time
      - '/etc/localtime:/etc/localtime:ro'
      - '/etc/timezone:/etc/timezone:ro'
    logging:
      options:
        max-size: '10m'
        max-file: '5'
```

mosquitto.conf:

```ini
max_queued_messages 1000

#pid_file /var/run/mosquitto.pid

# Configure ports and interfaces
# Port 1883 on all interfaces
listener 1883

# Allow anonymous access
allow_anonymous true

# Configure persistence for retained messages
persistence true
persistence_location /mosquitto/data/
persistence_file mosquitto.db

# Network configs
set_tcp_nodelay true
socket_domain ipv4

# Configure Logging
log_timestamp_format %Y-%m-%dT%H:%M:%S
log_dest file /mosquitto/log/mosquitto.log
log_dest stdout

# Configure file-based access
password_file /mosquitto/config/passwd

# Configure users access
acl_file /mosquitto/config/acls

# Add /mosquitto/config/conf.d to includes
include_dir /mosquitto/config/conf.d
```

acls:

```ini
topic #

user homie
topic homie/#
topic LSH/#
topic shellies/#
topic homeassistant/#

```

I've tried so far:

> set_tcp_nodelay false
> max_queued_messages 100
> Start over with an empty db

I'm unable to provide a clean log at the moment because I've some clients I cannot turn off
