### ISSUE TITLE
Change of permissions problem on docker

### ISSUE THREAD

**Issue by gabric098** [eclipse/mosquitto#1940]
Latest. (1.6.12) Docker.
I'm having the following issue which I suspect is due to some wrong setup on my side:
I've a stack defined in a docker compose file and the mosquitto section looks like this:
```
mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    ports:
      - "8883:8883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - mqtt-log:/mosquitto/log
      - mqtt-data:/mosquitto/data
      - /etc/localtime:/etc/localtime:ro
```

When I run the mosquitto container, the startup script `docker-entrypoint.sh` changes the owner to all the contents of `/mosquitto` (including the config files). This causes a change on ownershipt on the host and I'm not able to modify those files (unless using sudo) as the user on the host (a raspberry pi) is not the owner of those files anymore.

This is particularly annoying since I'm pulling docker-compose.yml and the whole config section from a github repo and I keep getting errors because the /mosquitto/config directory is not writable.

Any idea on how to avoid this issue?

Thank you
