### ISSUE TITLE
mqtt on docker, no file created in volumes

### ISSUE THREAD

**Issue by adizag** [eclipse/mosquitto#1958]
mosuitto installed through docker-compose on ubuntu 18.04.
In mosquitto volume, I have only empty folders. no conf/db/log files are created.

This is my compose conf:

```
    mqtt:
        restart: always
        hostname: mqtt
        container_name: mqtt
        image: eclipse-mosquitto:latest
        environment:
            - TZ=${TZ}  
        volumes:
            - ${USERDIR}/docker/mqtt/data:/mosquitto/data
            - ${USERDIR}/docker/mqtt/log:/mosquitto/log
        ports:
            - "1883:1883"
            - "9001:9001"
        user: "0:0"
```
I added the user 0:0 trying to let it write stuff there but it didn’t matter

Here is an output of permissions and files in it:
```
ezaguy@ezaguy-DELL:~/docker/mqtt$ ls -l -R
.:
total 8
drwxr-xr-x+ 2 root root 4096 Dec 13 00:42 data
drwxr-xr-x+ 2 root root 4096 Dec 13 00:42 log

./data:
total 0

./log:
total 0

```

What is wrong here? Why can't files be written?
