### ISSUE TITLE
No connection to port 1883

### ISSUE THREAD

**Issue by nicedevil007** [eclipse/mosquitto#2079]
heya, I run into an issue with my latest update on all my docker containers.
Everything is working except my eclipse-mosquitto one :(

I hope someone can help me out:

My docker stack yml looks like this:

```
version: "3.8"

volumes:
  mqtt_data:
  mqtt_config:
  mqtt_log:
  
networks:
 backend:

services:
  mqtt:
    image: eclipse-mosquitto
    hostname: mosquitto
    networks:
      backend:    
    ports:
      - 1883:1883/tcp
      - 9001:9001/tcp
    volumes:
      - mqtt_data:/mosquitto/data
      - mqtt_config:/mosquitto/config
      - mqtt_log:/mosquitto/log
    environment:
      TZ: "Europe/Vienna"
```

After the update to the lastest version I can't telnet to my host with port 1883 anymore.
What I found out so far is that any sent package to this container is going into the container (checked with `tcpdump -i any port 1883 -nn` inside the container) but nothing is coming back to the sending client of those packages.

This all was tested with freshly created volumes so the mosquitto.conf is the default one without any changes.
So connection via anonymous should be possilbe right?

I used mosquittoFX 1.7.1 to check if I even can connect to the broker without any luck :(

Hope someone can help me out?
