### ISSUE TITLE
docker - logging is stdout but volume for log is being created still

### ISSUE THREAD

**Issue by lustyffh** [eclipse/mosquitto#2147]
Hi,

I have set logging in the config file to the following:

```
log_dest stdout
log_type error
log_type warning
log_type notice
log_type information
```

![YlU92s5Twr](https://user-images.githubusercontent.com/9317589/112018535-b4f3a900-8b3f-11eb-9747-6d1376592c6f.png)

My docker-compose.yaml doesn't contain any reference to the logging volume:

```
version: '3.5'

services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    volumes:
      - ./config:/mosquitto/config/
      - ./data:/mosquitto/data/
    ports:
      - '1883:1883'
    networks:
      - default
    restart: unless-stopped

networks:
  default:
```

However, volume is still being created for the log location. Moreover, removing and recreating containers results in a new volume creation. While the old one is kept in place and results in the pile of unused volumes.

Please advise if this expected behavior. And how to avoid creating that volume.
