### ISSUE TITLE
Not authorised

### ISSUE THREAD

**Issue by Slyke** [eclipse/mosquitto#2240]
I'm running Mosquitto on a K3s cluster. Whenever I try to connect to it (using either MQTT Explorer or Tasmota) I get an error saying that the client is not authorised.

I suspect this is due to how the accounts are being salted, but unsure.

I have an initContainer that gets a passwd file from a secret and copies it to `/mosquitto/config/passwd` (`busybox`), then I have a second initContainer that runs `mosquitto_passwd -U /mosquitto/config/passwd` (`eclipse-mosquitto:2:latest`), before the actual Mosquitto container boots up (also `eclipse-mosquitto:2:latest`).

Here's my config file (in a configmap)
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config-cm
  namespace: home
data:
  mosquitto.conf.tmp: |
    persistence true
    persistence_location /mosquitto/data/
    log_dest stdout stderr file /mosquitto/log/mosquitto.log

    listener 1883
    protocol mqtt

    listener 9001
    protocol websockets

    allow_anonymous false
    password_file /mosquitto/config/passwd
    # cafile: /mosquitto/config/certs/ca.crt
    # certfile: /mosquitto/config/certs/server.crt
    # keyfile: /mosquitto/config/certs/server.key
```

Here is my deployment config:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: home
spec:
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      initContainers:
      - name: copy
        image: busybox
        command: ["/bin/sh", "-c", "cp /mosquitto/config/passwd.tmp /mosquitto/config/passwd && cp /mosquitto/config/mosquitto.conf.tmp /mosquitto/config/mosquitto.conf"]
        volumeMounts:
          - name: mosquitto-passwd
            mountPath: /mosquitto/config/passwd.tmp
            subPath: passwd.tmp
          - name: mosquitto-config
            mountPath: /mosquitto/config/mosquitto.conf.tmp
            subPath: mosquitto.conf.tmp
          - mountPath: /mosquitto
            name: mosquitto-dir
      - name: setup-passwd
        image: eclipse-mosquitto:2
        command: ["mosquitto_passwd", "-U", "/mosquitto/config/passwd"]
        volumeMounts:
          - mountPath: /mosquitto
            name: mosquitto-dir
      containers:
      - name: mosquitto
        image: eclipse-mosquitto:2
        resources:
          requests:
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 1883
          name: mosquitto-mqtt
          protocol: TCP
        - containerPort: 9001
          name: mosquitto-websk
          protocol: TCP
        volumeMounts:
          - mountPath: /mosquitto
            name: mosquitto-dir
      volumes:
        - name: mosquitto-config
          configMap:
            name: mosquitto-config-cm
            defaultMode: 420
        - name: mosquitto-passwd
          secret:
            secretName: mosquitto-passwd-secret
        - name: mosquitto-dir
          persistentVolumeClaim:
            claimName: mosquitto-dir
```

Is this happening because each Mosquitto container is trying to read the salted passwords differently?
