### ISSUE TITLE
Docker: mosquitto Error -> Unable to open include_dir 'conf.d/'

### ISSUE THREAD

**Issue by mrroot998** [eclipse/mosquitto#2243]
Hello everybody,

I'm encountering a problem in setting up mosquitto on docker:

```
mosquitto_1       | 1625043339: Error: Unable to open include_dir 'conf.d/'.
mosquitto_1       | 1625043339: Error found at /mosquitto/config/mosquitto.conf:6.
```

I want to use a file to configure mosquitto and that file is using another one for a more specific configuration.

here is the organisation for the service (for the moment the certificates are not used).

mosquitto/
├── .log
│   └── mosquitto.log
├── .data
└── .config
    ├── pwfile
    ├── passwd
    ├── mosquitto_message_timestamp.so
    ├── mosquitto.conf
    ├── conf.d
    │   └── default.conf
    ├── certs
    │   ├── serveur_broker.key
    │   ├── serveur_broker.crt
    │   ├── README
    │   └── CA_broker_mqtt.crt
    ├── ca_certificates
    │   ├── server_ca.crt
    │   ├── private_key.key
    │   ├── mqtt.test.perax.com.p12
    │   ├── broker_CA.crt
    │   └── README
    └── acl

Here is the details of the authorizations of files and folders:

```
drwxrwxrwx 5 ubuntu ubuntu 4096 Jun 30 09:00 .config
drwxrwxrwx 2   1883   1883 4096 Jun 24 07:31 .data
drwxrwxrwx 2 ubuntu ubuntu 4096 Jun 24 07:39 .log
```

(the user of data always changes after a `docker-compose up`)

in .config:
```
-rwxrwxrwx 1 ubuntu ubuntu  2086 Jun 24 07:32 acl
drwxrwxrwx 2 ubuntu ubuntu  4096 Jun 24 07:33 ca_certificates
drwxrwxrwx 2 ubuntu ubuntu  4096 Jun 30 09:09 certs
drwxrwxrwx 2 ubuntu ubuntu  4096 Jun 24 08:02 conf.d
-rwxrwxrwx 1   1883   1883   633 Jun 30 09:00 mosquitto.conf
-rwxrwxrwx 1 ubuntu ubuntu 16472 Jun 24 07:35 mosquitto_message_timestamp.so
-rwxrwxrwx 1 ubuntu ubuntu     0 Jun 24 07:36 passwd
-rwxrwxrwx 1 ubuntu ubuntu  3283 Jun 24 07:36 pwfile
```
(I gave all the authorizations for the tests)

in conf.d:
`
-rwxrwxrwx 1 ubuntu ubuntu  461 Jun 24 08:23 default.conf
`
Here is the mosquitto.conf file:

```
persistence true
persistence_location ../.data/

log_dest file ../.log/mosquitto.log

include_dir conf.d/

plugin ./mosquitto_message_timestamp.so

```

Here is the default.conf file:

```
#port 1883 est la connexion mqtt non chiffré
listener 1883
protocol mqtt

#port 8883 est la connexion mqtt chiffré
listener 8883
protocol mqtt

#protocol mqtt
allow_anonymous true
acl_file ./acl
password_file ./pwfile

cafile ../certs/CA_broker_mqtt.crt
certfile ../certs/serveur_broker.crt
keyfile ../certs/serveur_broker.key
tls_version tlsv1.2
#require_certificate true

# Uncomment to use ssl
use_identity_as_username true

#use_subject_as_username true
```
And finally here is the docker-compose part for the moquitto container:

```
  mosquitto:
    restart: always
    image: "eclipse-mosquitto"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/.config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/.data/:/mosquitto/data/
      - ./mosquitto/.log/mosquitto.log:/mosquitto/log/mosquitto.log
#    user: 1883:1883
#    environment:
#      - PUID=1883
#      - PGID=1883

```

In thanking you a lot for your help.
