### ISSUE TITLE
Password file fails to work between reboots

### ISSUE THREAD

**Issue by Slyke** [eclipse/mosquitto#2295]
I have Mosquitto running on a K8s cluster.

I have the config file set in a config map:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config-cm
  namespace: home
data:
  mosquitto.conf.tmp: |
    persistence true
    persistence_location /mosquitto/data/
    log_dest stdout stderr file /mosquitto/log/mosquitto.log

    listener 1883
    protocol mqtt

    listener 9001
    protocol websockets

    allow_anonymous false
    password_file /mosquitto/config/passwd
```

The `password_file /mosquitto/config/passwd` is commented out on first boot.

If I create a passwd file within the pod using using any of the following commands:
```
mosquitto_passwd -c /mosquitto/config/passwd <USER>
mosquitto_passwd -b /mosquitto/config/passwd <USER> <PASS>
mosquitto_passwd -U /mosquitto/config/passwd
```

(I only use `-U` if passwords were mounted plaintext)

And restart the pod, the pod reports the following error:
```
1630485093: mosquitto version 2.0.11 starting
1630485093: Config loaded from /mosquitto/config/mosquitto.conf.
1630485093: Error: Unable to open pwfile "/mosquitto/config/passwd".
1630485093: Error opening password file "/mosquitto/config/passwd".
```

Using an init container, I'm checking permissions of the `/mosquitto/config/` directory:
```
$ ls -ahl /mosquitto/config
total 8K
drwxrwxrwx    1 root     root         40 Sep  1 08:30 .
drwxrwxrwx    1 root     root         26 Sep  1 08:05 ..
-rw-r--r--    1 root     root         372 Sep  1 08:30 mosquitto.conf
-rw-r--r--    1 root     root         739 Sep  1 08:30 passwd

$ whoami
root
```

I have also attempted to chown to the `1883` user:

```
$ ls -ahl /mosquitto/config
total 8K
drwxrwxrwx    1 1883     1883          40 Sep  1 08:30 .
drwxrwxrwx    1 1883     1883          26 Sep  1 08:05 ..
-rw-r--r--    1 1883     1883         372 Sep  1 08:30 mosquitto.conf
-rw-r--r--    1 1883     1883         739 Sep  1 08:30 passwd

$ whoami
root
```

I can cat the file just fine from within the init container:
```
$ ls -ahl /mosquitto/config
total 8K
drwxrwxrwx    1 1883     1883          40 Sep  1 08:30 .
drwxrwxrwx    1 1883     1883          26 Sep  1 08:05 ..
-rw-r--r--    1 1883     1883         372 Sep  1 08:30 mosquitto.conf
-rw-r--r--    1 1883     1883         739 Sep  1 08:30 passwd

$ whoami
root

$ cat /mosquitto/config/passwd
testuser:$7$101$zdBc5H5p7BDEGNH2$UVrkkkxXbDCpNt+OM97bnRCAIZbJGZ6K9MhdfubOZoFQrlAfLqIFJvwxXy46tlvDvCGGUbLlP0KBfeTCUcErdw==
```

Hashed password is `qwerty`

**Comment by Slyke** [comment]
This should be working?
```
# mosquitto -c /mosquitto/config/mosquitto.conf
1630563868: mosquitto version 2.0.11 starting
1630563868: Config loaded from /mosquitto/config/mosquitto.conf.
1630563868: Error: Unable to open pwfile "/mosquitto/config/passwd".
1630563868: Error opening password file "/mosquitto/config/passwd".


/ # ls -ahl /mosquitto/config/
total 8K
drwxrwx---    1 mosquitt mosquitt      40 Sep  2 06:21 .
drwxrwxrwx    1 mosquitt mosquitt      26 Sep  1 08:05 ..
-rwxrwx---    1 mosquitt mosquitt     372 Sep  2 06:21 mosquitto.conf
-rwxrwx---    1 mosquitt mosquitt     739 Sep  2 06:21 passwd


/ # cat /mosquitto/config/mosquitto.conf
persistence true
persistence_location /mosquitto/data/
log_dest stdout stderr file /mosquitto/log/mosquitto.log

listener 1883
protocol mqtt

listener 9001
protocol websockets

allow_anonymous false
password_file /mosquitto/config/passwd
# cafile: /mosquitto/config/certs/ca.crt
# certfile: /mosquitto/config/certs/server.crt
# keyfile: /mosquitto/config/certs/server.key


/ # cat /mosquitto/config/passwd
testuser:$7$101$zdBc5H5p7BDEGNH2$UVrkkkxXbDCpNt+OM97bnRCAIZbJGZ6K9MhdfubOZoFQrlAfLqIFJvwxXy46tlvDvCGGUbLlP0KBfeTCUcErdw==
```

**Comment by Slyke** [comment]
Sure, this should work:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: home
spec:
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 60
              preference:
                matchExpressions:
                - key: general-schedule
                  operator: In
                  values:
                  - "true"
      initContainers: # Can comment out these init containers so that no files are touched/changed when the pod starts for testing.
      - name: copy
        image: busybox
        command: ["/bin/sh", "-c", "mkdir -p /mosquitto/config && mkdir -p /mosquitto.tmp/config && rm /mosquitto/config/mosquitto.conf; cp /mosquitto.tmp/config/mosquitto.conf.tmp /mosquitto/config/mosquitto.conf && rm /mosquitto/config/passwd; cp /mosquitto.tmp/config/passwd.tmp /mosquitto/config/passwd"]
        volumeMounts:
          - name: mosquitto-passwd
            mountPath: /mosquitto.tmp/config/passwd.tmp
            subPath: passwd.tmp
          - name: mosquitto-config
            mountPath: /mosquitto.tmp/config/mosquitto.conf.tmp
            subPath: mosquitto.conf.tmp
          - mountPath: /mosquitto
            name: mosquitto-dir
      - name: setup-passwd
        image: eclipse-mosquitto:2
        imagePullPolicy: IfNotPresent
        command: ["mosquitto_passwd", "-U", "/mosquitto/config/passwd"]
        volumeMounts:
          - mountPath: /mosquitto
            name: mosquitto-dir
      - name: permissions-update
        image: busybox
        command: ["/bin/sh", "-c", "chown -R 1883:1883 /mosquitto/config; chmod -R 770 /mosquitto/config"]
        volumeMounts:
          - mountPath: /mosquitto
            name: mosquitto-dir
      - name: permissions-check
        image: busybox
        command: ["/bin/sh", "-c", "ls -ahl /mosquitto/config"]
        volumeMounts:
          - mountPath: /mosquitto
            name: mosquitto-dir
      containers:
      - name: mosquitto
        image: eclipse-mosquitto:2
        # command: ["/bin/sh"] # Uncomment these 2 lines if pod is crashing to debug
        # args: ["-c", "while true; do echo hello; sleep 600;done"]
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 1883
          name: mosquitto-mqtt
          protocol: TCP
        - containerPort: 9001
          name: mosquitto-websk
          protocol: TCP
        volumeMounts:
          - mountPath: /mosquitto
            name: mosquitto-dir
        env:
        - name: PUID
          value: "1883"
        - name: PGID
          value: "1883"
      volumes:
        - name: mosquitto-config
          configMap:
            name: mosquitto-config-cm
            defaultMode: 420
        - name: mosquitto-passwd
          secret:
            secretName: mosquitto-passwd-secret
        - name: mosquitto-dir
          persistentVolumeClaim:
            claimName: mosquitto-dir
---
apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-passwd-secret
  namespace: home
type: Opaque
stringData:
  passwd.tmp: |
    testuser:qwerty
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config-cm
  namespace: home
data:
  mosquitto.conf.tmp: |
    persistence true
    persistence_location /mosquitto/data/
    log_dest stdout stderr file /mosquitto/log/mosquitto.log

    listener 1883
    protocol mqtt

    listener 9001
    protocol websockets

    allow_anonymous false
    password_file /mosquitto/config/passwd
    # cafile: /mosquitto/config/certs/ca.crt
    # certfile: /mosquitto/config/certs/server.crt
    # keyfile: /mosquitto/config/certs/server.key
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: home
  labels:
    app: mosquitto
  name: mosquitto-dir
spec:
  storageClassName: ""
  volumeName: mosquitto-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mosquitto-pv
  namespace: home
spec:
  storageClassName: ""
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=3
  nfs:
    server: nas
    path: "/volume4/kubes/home/mosquitto"
    readOnly: false
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mosquitto
  name: mosquitto
  namespace: home
spec:
  externalTrafficPolicy: Local
  ports:
  - name: mosquitto-mqtt
    protocol: TCP
    port: 1883
    targetPort: mosquitto-mqtt
  - name: mosquitto-websk
    protocol: TCP
    port: 9001
    targetPort: mosquitto-websk
  selector:
    app: mosquitto
  loadBalancerIP: 192.168.1.234
  type: LoadBalancer


```

**Comment by Daedaluz** [comment]
is there any particular reason to why you want clear-text passwd file as a secret?
it adds a lot of complexity to make it right for the mosquitto pod.

personally i would just use the hashed version directly as a secret and update / modify the passwd file with local tools.

But; i'm not sure if the NFS is remounted over the different steps of init containers you have, and i have someting nagging my back head about permissions and NFS that it dafault "squashes" permissions to root. Your permission changes made by the init containers might therefore be futile if this is the case.

try run mosquitto as root instead just to see if you can make it work that way and verify the issue.

**Comment by Slyke** [comment]
> is there any particular reason to why you want clear-text passwd file as a secret?

That's how how it's stored in the secret for Kubernetes. The init container runs the hashing each boot from the clear text secret.

```
initContainers: # Can comment out these init containers so that no files are touched/changed when the pod starts for testing.
      - name: copy
        image: busybox
        command: ["/bin/sh", "-c", "mkdir -p /mosquitto/config && mkdir -p /mosquitto.tmp/config && rm /mosquitto/config/mosquitto.conf; cp /mosquitto.tmp/config/mosquitto.conf.tmp /mosquitto/config/mosquitto.conf && rm /mosquitto/config/passwd; cp /mosquitto.tmp/config/passwd.tmp /mosquitto/config/passwd"]
        volumeMounts:
          - name: mosquitto-passwd
            mountPath: /mosquitto.tmp/config/passwd.tmp
            subPath: passwd.tmp
          - name: mosquitto-config
            mountPath: /mosquitto.tmp/config/mosquitto.conf.tmp
            subPath: mosquitto.conf.tmp
          - mountPath: /mosquitto
            name: mosquitto-dir
      - name: setup-passwd
        image: eclipse-mosquitto:2
        imagePullPolicy: IfNotPresent
        command: ["mosquitto_passwd", "-U", "/mosquitto/config/passwd"] # This will be plaintext password that's mounted from the secret, so we need to use -U to hash
        volumeMounts:
          - mountPath: /mosquitto
            name: mosquitto-dir
      - name: permissions-update
        image: busybox
        command: ["/bin/sh", "-c", "chown -R 1883:1883 /mosquitto/config; chmod -R 770 /mosquitto/config"]
        volumeMounts:
          - mountPath: /mosquitto
            name: mosquitto-dir
```

The reason I did it this way is that running `mosquitto_passwd -U` on a file that already has hashes breaks the existing hashes, and I need to exec into the pod. If it's stored in a secret and hashed at boot time, it's as easy as editing the secret and restarting the pod.

I have tried disabling all the init containers & using an existing prehashed passwd file, but still get the same error.

> Your permission changes made by the init containers might therefore be futile if this is the case.

I disabled mosquitto from starting up (by uncommenting the `command` and `args` lines to just run a sleep loop) and exec'd into the pod and tried to run `mosquitto -c /mosquitto/config/mosquitto.conf` manually, after checking permissions and ownership (init containers were on for this test):

```
$ kubectl exec --stdin --tty $(kubectl get pods -n home | grep mosquitto | cut -d ' ' -f1) -n home -- /bin/sh
Defaulted container "mosquitto" out of: mosquitto, copy (init), setup-passwd (init), permissions-update (init), permissions-check (init)
/ # cat /mosquitto/config/passwd
testuser:$7$101$gErFdvHjuEdHW2RI$F35yilvrtiEF2RP17WtbT0TiqAxWh+zTs3F5c9hQ/NrNXSqMR96fsCaNsps3Hi3FHRzeQsTlWocqOG6oMHMUbw==
/ # cat /mosquitto/config/mosquitto.conf
persistence true
persistence_location /mosquitto/data/
log_dest stdout stderr file /mosquitto/log/mosquitto.log

listener 1883
protocol mqtt

listener 9001
protocol websockets

allow_anonymous false
password_file /mosquitto/config/passwd
# cafile: /mosquitto/config/certs/ca.crt
# certfile: /mosquitto/config/certs/server.crt
# keyfile: /mosquitto/config/certs/server.key
/ # ls -ahl /mosquitto/config/
total 8K
drwxrwx---    1 mosquitt mosquitt      40 Sep  2 09:34 .
drwxrwxrwx    1 mosquitt mosquitt      26 Sep  1 08:05 ..
-rwxrwx---    1 mosquitt mosquitt     372 Sep  2 09:34 mosquitto.conf
-rwxrwx---    1 mosquitt mosquitt     122 Sep  2 09:34 passwd
/ # mosquitto -c /mosquitto/config/mosquitto.conf
1630575313: mosquitto version 2.0.11 starting
1630575313: Config loaded from /mosquitto/config/mosquitto.conf.
1630575313: Error: Unable to open pwfile "/mosquitto/config/passwd".
1630575313: Error opening password file "/mosquitto/config/passwd".
/ #
```

**Comment by Slyke** [comment]
Here is my attempt running with root:
```
/ # cat /mosquitto/config/passwd
testuser:$7$101$gErFdvHjuEdHW2RI$F35yilvrtiEF2RP17WtbT0TiqAxWh+zTs3F5c9hQ/NrNXSqMR96fsCaNsps3Hi3FHRzeQsTlWocqOG6oMHMUbw==

/ # cat /mosquitto/config/mosquitto.conf
persistence true
persistence_location /mosquitto/data/
log_dest stdout stderr file /mosquitto/log/mosquitto.log

listener 1883
protocol mqtt

listener 9001
protocol websockets

allow_anonymous false
password_file /mosquitto/config/passwd
# cafile: /mosquitto/config/certs/ca.crt
# certfile: /mosquitto/config/certs/server.crt
# keyfile: /mosquitto/config/certs/server.key

/ # ls -ahl /mosquitto/config/
total 8K
drwxrwx---    1 mosquitt mosquitt      40 Sep  2 09:34 .
drwxrwxrwx    1 mosquitt mosquitt      26 Sep  1 08:05 ..
-rwxrwx---    1 mosquitt mosquitt     372 Sep  2 09:34 mosquitto.conf
-rwxrwx---    1 mosquitt mosquitt     122 Sep  2 09:34 passwd

/ # su - root mosquitto -c /mosquitto/config/mosquitto.conf
/mosquitto/config/mosquitto.conf: line 1: persistence: not found
/mosquitto/config/mosquitto.conf: line 2: persistence_location: not found
/mosquitto/config/mosquitto.conf: line 3: log_dest: not found
/mosquitto/config/mosquitto.conf: line 5: listener: not found
/mosquitto/config/mosquitto.conf: line 6: protocol: not found
/mosquitto/config/mosquitto.conf: line 8: listener: not found
/mosquitto/config/mosquitto.conf: line 9: protocol: not found
/mosquitto/config/mosquitto.conf: line 11: allow_anonymous: not found
/mosquitto/config/mosquitto.conf: line 12: password_file: not found

/ # chmod 775 /mosquitto/config/mosquitto.conf

/ # su - root mosquitto -c /mosquitto/config/mosquitto.conf
/mosquitto/config/mosquitto.conf: line 1: persistence: not found
/mosquitto/config/mosquitto.conf: line 2: persistence_location: not found
/mosquitto/config/mosquitto.conf: line 3: log_dest: not found
/mosquitto/config/mosquitto.conf: line 5: listener: not found
/mosquitto/config/mosquitto.conf: line 6: protocol: not found
/mosquitto/config/mosquitto.conf: line 8: listener: not found
/mosquitto/config/mosquitto.conf: line 9: protocol: not found
/mosquitto/config/mosquitto.conf: line 11: allow_anonymous: not found
/mosquitto/config/mosquitto.conf: line 12: password_file: not found

/ # ls -ahl /mosquitto/config/
total 8K
drwxrwx---    1 mosquitt mosquitt      40 Sep  2 09:34 .
drwxrwxrwx    1 mosquitt mosquitt      26 Sep  1 08:05 ..
-rwxrwxr-x    1 mosquitt mosquitt     372 Sep  2 09:34 mosquitto.conf
-rwxrwx---    1 mosquitt mosquitt     122 Sep  2 09:34 passwd
```

**Comment by Daedaluz** [comment]
so, i tweaked your deployment a bit to fit my own cluster; this works.
```
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: home
  name: mosquitto-dir
  labels:
    app: mosquitto
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
---
apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-passwd-secret
  namespace: home
type: Opaque
stringData:
  passwd.tmp: |
    testuser:qwerty
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config-cm
  namespace: home
data:
  mosquitto.conf: |
    user mosquitto
    persistence true
    persistence_location /mosquitto/data/
    log_dest stdout stderr file /mosquitto/log/mosquitto.log

    listener 1883
    protocol mqtt

    listener 9001
    protocol websockets

    allow_anonymous false
    password_file /mosquitto/config/passwd
    # cafile: /mosquitto/config/certs/ca.crt
    # certfile: /mosquitto/config/certs/server.crt
    # keyfile: /mosquitto/config/certs/server.key
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: home
spec:
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      initContainers:
      - name: passwd
        image: eclipse-mosquitto:2.0.11
        imagePullPolicy: Always
        command: [
          "/bin/sh", "-c", "mkdir -p /mosquitto/config || true && cp /mosquitto.tmp/passwd.tmp /mosquitto/config/passwd && mosquitto_passwd -U /mosquitto/config/passwd"
        ]
        volumeMounts:
          - mountPath: /mosquitto
            name: mosquitto-dir
          - mountPath: /mosquitto.tmp/passwd.tmp
            name: mosquitto-passwd
            subPath: passwd.tmp
      containers:
      - name: mosquitto
        image: eclipse-mosquitto:2.0.11
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 1883
          name: mosquitto-mqtt
          protocol: TCP
        - containerPort: 9001
          name: mosquitto-websk
          protocol: TCP
        volumeMounts:
          - mountPath: /mosquitto
            name: mosquitto-dir
          - mountPath: /mosquitto/config/mosquitto.conf
            name: mosquitto-config
            subPath: mosquitto.conf
      volumes:
        - name: mosquitto-config
          configMap:
            name: mosquitto-config-cm
            defaultMode: 420
        - name: mosquitto-passwd
          secret:
            secretName: mosquitto-passwd-secret
        - name: mosquitto-dir
          persistentVolumeClaim:
            claimName: mosquitto-dir
---
```

The changes i made:

* Added `user mosquitto` at top of configuration
* removed several init containers (only one left to do the actual work of copying and hashing.)
* Renamed file in mosquitto-config-cm to `mosquitto.conf`
* Directly mounted the configuration file, instead of copying
* Removed those environments of PUID + PGID
* Tweaked pvc to fit my cluster. (this shouldn't have ony effect on the problem though)
* Removed the service to reduce clutter. (shouldn't have any effect on the problem either)

So, i noticed that the mosquitto container does it's own chmod + chowning if it runs as root, so no need to do it in init containers.
Mosquitto also drops permissions once started so no need to change user / group prior to running mosquitto.
