### ISSUE TITLE
"Error obtaining system time" when starting mosquitto docker container

### ISSUE THREAD

**Issue by olylak** [eclipse/mosquitto#2299]
Hi there,

I'm getting the following error when starting mosquitto docker container: **"Error obtaining system time"**
Nothing in the log file. Until today everything was working as expected.

```
@raspberrypi:/home/docker $ sudo docker-compose up mosquitto
Building with native build. Learn about native build in Compose here: https://docs.docker.com/go/compose-native-build/
Pulling mosquitto (eclipse-mosquitto:latest)...
latest: Pulling from library/eclipse-mosquitto
2e78c0f86ba9: Pull complete
0e6948c3b790: Pull complete
d128613bb1ac: Pull complete
Digest: sha256:ce08d3fe69d4170cea2426739af86ac95e683f01dd2c4141da661983a2401364
Status: Downloaded newer image for eclipse-mosquitto:latest
Creating mosquitto ... done
Attaching to mosquitto
mosquitto        | Error obtaining system time.
```

Config file:
```
persistence true
persistence_location /mosquitto/data/
log_dest stdout
log_dest file /mosquitto/log/mosquitto.log
log_type all
log_timestamp_format %Y-%m-%dT%H:%M:%S

connection_messages true
set_tcp_nodelay true
max_keepalive 65535
max_connections -1
listener 1883
allow_anonymous true
```

Docker compose file
```
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    restart: always
    networks:
      home_automation:
        aliases:
          - mqtt-broker
    ports:
      - '1883:1883'
    volumes:
      - './mosquitto/config:/mosquitto/config'
      - './mosquitto/log:/mosquitto/log'
      - './mosquitto/data:/mosquitto/data'
```
