### ISSUE TITLE
Mosquitto hanging on startup in docker image when log_dest = stdout

### ISSUE THREAD

**Issue by alexmcorrigan** [eclipse/mosquitto#2338]
I am running the latest eclipse-mosquitto docker image (currently 2.0.12) on a raspberry pi 4 with 'Raspian GNU /Linux 10 (buster)'.

I find that when I mount a config file that specifies `log_dest` to file:

`log_dest file /mosquitto/log/mosquitto.log`

... the broker starts up straight away, accepts connections, receives and forwards messages etc.

However, when I mount the same config file but with `log_dest` to stdout:

`log_dest stdout`

... the broker startup hangs on `<timestamp>: mosquitto version 2.0.12 starting` and doesn't progress any further, accepts no connections etc.

I believe this very much related to the issue reported in this ticket: https://github.com/eclipse/mosquitto/issues/773, but that seems to have been closed early before resolution.

I'm not sure what else to be looking at to investigate further, so please advise next steps to look into this.

My preference would be to not persist logs inside the docker container but have an external service collect them through the docker interface, hence wanting the stdout option.

The complete config file I am using:

```
persistence false
log_dest stdout
connection_messages true
listener 1883
allow_anonymous true
```

**Comment by aeciolevy** [comment]
I am getting the same issue
OS: macOS 12.3
Docker: 20.10.17, build 100c701

this is my mosquitto.conf

```
#log_type error
log_type notice
log_type information
log_type debug
log_type websockets
#log_type all
connection_messages true
#log_dest topic
log_dest stdout
#allow_anonymous false
#Extra Listeners
listener 9001
protocol websockets
websockets_log_level 6

listener 1883 0.0.0.0
allow_anonymous true
```

I get this output when I run
```
docker run -it -p 1883:1883 -p 9001:9001 -v ${PWD}/config/mosquitto.conf:/config/mosquitto.conf -v ${PWD}/data -v ${PWD}/log eclipse-mosquitto
```

``` 
1662151909: mosquitto version 2.0.15 starting
1662151909: Config loaded from /mosquitto/config/mosquitto.conf.
1662151909: Starting in local only mode. Connections will only be possible from clients running on this machine.
1662151909: Create a configuration file which defines a listener to allow remote access.
1662151909: For more details see https://mosquitto.org/documentation/authentication-methods/
1662151909: Opening ipv4 listen socket on port 1883.
1662151909: Opening ipv6 listen socket on port 1883.
1662151909: Error: Address not available
1662151909: mosquitto version 2.0.15 running
```

If I use the docker-compose.yml
```
version: '3.1'
services:
  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    network_mode: host
    volumes:
      - $PWD/config:/mosquitto/config
      - $PWD/data:/mosquitto/data
      - $PWD/log:/mosquitto/log
```

I get this
```
[+] Running 1/0
 ⠿ Container mosquitto  Created                                                                                    0.0s
Attaching to mosquitto
mosquitto  | 1662152214: mosquitto version 2.0.15 starting
```

**Comment by DavidVonRueden** [comment]
!!! EDIT:

I was also just thrown off by the docker compose not really stopping. Thats because I was missing the "-d" flag. Now it properly detaches after creation and connections can be established.

Hi,
I am running into the same issue. I tested it on two machines on the same network with the same outcome.
My .conf
```
persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log
log_dest stdout
password_file /mosquitto/config/mosquitto.passwd
allow_anonymous false
listener 9001
listener 1883
```
my compose.yaml

```
services:
  mosquitto:
    image: eclipse-mosquitto
    stdin_open: true
    tty: true
    restart: unless-stopped
    container_name: mosquitto
    volumes:
      - /home/user/mosquitto/config:/mosquitto/config
      - /home/user/mosquitto/data:/mosquitto/data
      - /home/user/mosquitto/log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"
```

Does anybody have an idea whats causing this?
