### ISSUE TITLE
Error: Address in use when deploying MQTT 2.0.14 as container using Docker Desktop

### ISSUE THREAD

**Issue by RiteshKo** [eclipse/mosquitto#2428]
I am trying to run mqtt as a container using Docker desktop. But as per the logs getting an error **Address in use** when running the command: 

 ` mosquitto -c mosquitto.conf`

Below is my docker-compose file:

```
version: '3.5'

services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto_container
    ports:
      - 1883:1883
    volumes:
      - ./config:/mosquitto/config

```
And the mosquitto.conf file:

```
listener 1883 127.0.0.1
allow_anonymous true 
```
In all the articles over the internet and also in the mqtt docs it is mentioned that we have to specify listener in the conf file which I have added. 

My goal is to run mqtt as a container and then from a .net utililty publish the messages to the broker.

I am using the Docker version v20.10.10 running on my Windows 10 and mqtt image version is 2.0.14.

Please guide me.
