### ISSUE TITLE
What is the right way to configure eclipse-mosquitto in a docker-compose file so that it uses a mosquitto.conf file in a volume?

### ISSUE THREAD

**Issue by spierepf** [eclipse/mosquitto#2512]
No matter how I configure my `docker-compose.yml` file in order to run eclipse-mostquitto using a custom mosquitto.conf file, I keep getting a variation on the following error message:

# docker-compose up eclipse-mosquitto
server_eclipse-mosquitto_1 is up-to-date
Attaching to server_eclipse-mosquitto_1
eclipse-mosquitto_1  | chown: /mosquitto/config: Permission denied
eclipse-mosquitto_1  | 1650310347: Error: Unable to open config file /mosquitto/config/mosquitto.conf.

I've tried ever suggestion in https://github.com/eclipse/mosquitto/issues/1078 but I keep getting that error.

Is there an 'official' supported way to configure eclipse-mosquitto as a member of a docker-compose?

**Comment by danielmoncada** [comment]
I have mine setup like this:

```yaml
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto_broker
    volumes:
      - ./mosquitto/:/mosquitto/:rw
    ports:
      - 1883:1883
      - 9001:9001
    networks:
        - default
```

and then a folder structure like this:

- docker compose
- mosquitto
   - config
      - mosquitto.conf

**Comment by spierepf** [comment]
Who are the owners and what are the permissions on the files? That appears to be where my system is stumbling.

**Comment by spierepf** [comment]
I tried your config. (All files owned by root with normal permissions:

```
# docker-compose up mosquitto
Creating mosquitto_broker ... done
Attaching to mosquitto_broker
mosquitto_broker  | chown: /mosquitto: Permission denied
mosquitto_broker  | 1650595839: Error: Unable to open config file /mosquitto/config/mosquitto.conf.
mosquitto_broker exited with code 3
```

**Comment by danielmoncada** [comment]
> I tried your config. (All files owned by root with normal permissions:
> 
> ```
> # docker-compose up mosquitto
> Creating mosquitto_broker ... done
> Attaching to mosquitto_broker
> mosquitto_broker  | chown: /mosquitto: Permission denied
> mosquitto_broker  | 1650595839: Error: Unable to open config file /mosquitto/config/mosquitto.conf.
> mosquitto_broker exited with code 3
> ```

yeah, that's weird. everyone on my team is doing the same thing with no permission problems.

have you tried running ```docker-compuse up``` as ```sudo```?

**Comment by ThePrankMonkey** [comment]
I was able to resolve mine by doing the following two things:
1. NOT SURE IF THIS STEP NEEDED, `chmod 777 -R .` in the folder with my compose file.
2. I added an empty config file at `./mosquitto/config/mosquitto.conf` in my local side of the volume. I guess the container won't attempt to make a new config file when starting up?

You'll need to fill in some blanks on the config file per https://mosquitto.org/man/mosquitto-conf-5.html

**Comment by blackandcold** [comment]
I have the same problem on MacOS Colima vz / docker setup.
777 is never a good idea (and doesn't fix the problem either) anywhere and the :rw appended does not change anything.

` docker compose up mosquitto
[+] Running 1/1
 ✔ Container mosquitto  Recreated                                                                                                                                                                          0.0s
Attaching to mosquitto
mosquitto  | chown: /mosquitto/.DS_Store: Permission denied
mosquitto  | chown: /mosquitto/config/mosquitto.conf: Permission denied
mosquitto  | chown: /mosquitto/config: Permission denied
mosquitto  | chown: /mosquitto/config: Permission denied
mosquitto  | chown: /mosquitto/log/mosquitto.log: Permission denied
mosquitto  | chown: /mosquitto/log: Permission denied
mosquitto  | chown: /mosquitto/log: Permission denied
mosquitto  | chown: /mosquitto/data/mosquitto.db: Permission denied
mosquitto  | chown: /mosquitto/data: Permission denied
mosquitto  | chown: /mosquitto/data: Permission denied
mosquitto  | chown: /mosquitto: Permission denied
mosquitto  | chown: /mosquitto: Permission denied
mosquitto  | 1744990253: Warning: File /mosquitto/data//mosquitto.db owner is not mosquitto. Future versions will refuse to load this file.To fix this, use `chown mosquitto /mosquitto/data//mosquitto.db`.
mosquitto  | 1744990253: Warning: File /mosquitto/data//mosquitto.db group is not mosquitto. Future versions will refuse to load this file.
Gracefully stopping... (press Ctrl+C again to force)
[+] Stopping 1/1
 ✔ Container mosquitto  Stopped`

**Comment by fedorkk** [comment]
If someone still land on this page with the same issue, I found a particular problem related to the SELinux policies. On my home laptop with Linux Mint docker container worked without any issues, bun on the remote machine with Fedora Server I got the same error: `Error: Unable to open config file /mosquitto/config/mosquitto.conf.`
The solution is - adding `:Z` to the end of mounting insruction in the `docker-compose.yml`. It allows read/write access to mounted files.
In the end my config file looks like that:
```
mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    user: 1000:1000
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config:Z
      - ./mosquitto/data:/mosquitto/data:Z
      - ./mosquitto/log:/mosquitto/log:Z
    restart: unless-stopped
    networks:
      - mqtt
```
The `user` derictive uses `UID` and `GUID` of the local user, so mosquito don't change file permissions to `root:root` on start.
