### ISSUE TITLE
Connection Error with eclipse mosquitto

### ISSUE THREAD

**Issue by Yingliangzhe** [eclipse/mosquitto#2654]
Hello everyone, 
I'm trying to use the **eclipse-mosquitto docker image latest** as the mqtt server. The Container is running on a **Ubuntu amd64** System
The server was started with a config file named mosquitto.conf and was mounted on :

```
persistence true
persistence_location /mosquitto/data/

user mosquitto

listener 1883
allow_anonymous true

log_dest file /mosquitto/log/mosquitto.log
log_dest stdout
```

docker-compose.yaml
```
mqtt:
    <<: *logging_var
    image: "eclipse-mosquitto"
    networks:
      - sam-net
    env_file:
      - .env
    ports:
      - "6214:1883"
    volumes:
      - "./config_dir/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf"
    restart: always
```

But as I was trying to publish some message on that server with 
`mosquitto_sub -h localhost -p 6214 -t test -d`
and 
`mosquitto_pub -h localhost -p 6214 -t test -m "test_msg" -d`

it throws errors from pub side like:

```
Client mosq-4qRzmwb7VJlDMKNWul sending CONNECT
Error: The connection was lost.
```

Thank you!
