### ISSUE TITLE
Custom mosquitto.conf being ignored under Docker

### ISSUE THREAD

**Issue by rraug** [eclipse/mosquitto#2809]
I've set up a mosquitto Container under Docker. The OS is CentOS Stream 9 with Docker Version 23.0.1.
Unfortunately, it seems that mosquitto is not loading my custom mosquitto.conf I provided in the docker-compose.yml. 
So far I tried:
- Checked if the custom configuration file is accessible within the container. It is.
- Different mosquitto versions/tags
- Stopped and deleted the old mosquitto containers, rebooted the system

I was able to reproduce the issue on a different CentOS installation.
Could that be some kind of bug or am I overlooking something?
```sh
/ # mosquitto
1683843618: mosquitto version 2.0.15 starting
1683843618: Using default config.
1683843618: Starting in local only mode. Connections will only be possible from clients running on this machine.
1683843618: Create a configuration file which defines a listener to allow remote access.
1683843618: For more details see https://mosquitto.org/documentation/authentication-methods/
1683843618: Opening ipv4 listen socket on port 1883.
1683843618: Opening ipv6 listen socket on port 1883.
1683843618: Error: Address not available
1683843618: mosquitto version 2.0.15 running
```

docker-compose.yml:
```yml
---
version: '3.7'

services:
  mosquitto:
    image: eclipse-mosquitto:2.0.15
    container_name: mosquitto
    restart: always
    volumes:
      - /opt/mosquitto/config:/mosquitto/config
      - /opt/mosquitto/mosquitto/data:/mosquitto/data
      - /opt/mosquitto/mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001
```
mosquitto.conf:
```yml
persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log
listener 127.0.0.1:1883

## Authentication ##
allow_anonymous true
```
