### ISSUE TITLE
2.0.5+ doesn't work, 2.0.4- does.

### ISSUE THREAD

**Issue by MilorES** [eclipse/mosquitto#3029]
RUN
```
services:
  mqtt:
    container_name: mosquitto
    image: eclipse-mosquitto:2.0.4
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./config:/mosquitto/config
      - ./logs:/mosquitto/log
      - ./data:/mosquitto/data
    restart: always
    environment:
      - TZ=Europe/Madrid
```

```
mosquitto  | 1712062032: mosquitto version 2.0.4 starting
mosquitto  | 1712062032: Config loaded from /mosquitto/config/mosquitto.conf.
mosquitto  | 1712062032: Opening ipv4 listen socket on port 1883.
mosquitto  | 1712062032: Binding listener to interface "eth0".
mosquitto  | 1712062032: Opening ipv6 listen socket on port 1883.
mosquitto  | 1712062032: Binding listener to interface "eth0".
mosquitto  | 1712062032: mosquitto version 2.0.4 running
mosquitto  | 1712062032: New connection from xxx.xxx.xxx.xxx:59079 on port 1883.
mosquitto  | 1712062032: New client connected from xxx.xxx.xxx.xxx59079 as mqtt-explorer-1d62a80b (p2, c1, k60, u'user').
```
NOT RUN
```
services:
  mqtt:
    container_name: mosquitto
    image: eclipse-mosquitto:2.0.5
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./config:/mosquitto/config
      - ./logs:/mosquitto/log
      - ./data:/mosquitto/data
    restart: always
    environment:
      - TZ=Europe/Madrid
```

```
mosquitto  | 1712061947: mosquitto version 2.0.5 starting
mosquitto  | 1712061947: Config loaded from /mosquitto/config/mosquitto.conf.
mosquitto  | 1712061947: Opening ipv4 listen socket on port 1883.
mosquitto  | 1712061947: Opening ipv6 listen socket on port 1883.
mosquitto  | 1712061947: Error: Invalid argument
```
