### ISSUE TITLE
How to add this syntax 'mosquitto -c /mosquitto-no-auth.conf' to docker-compose.yml file ?

### ISSUE THREAD

**Issue by luan-dang-techlabs** [eclipse/mosquitto#3061]
How do I add this syntax in docker-compose.yml file?

```
 mosquitto -c /mosquitto-no-auth.conf
```

Command Line:

```

docker run --rm -it --name mosquitto_name --network=host -v /home/tmp/mosquitto/data:/mosquitto/data -v /home/tmp/mosquitto/log:/mosquitto/log eclipse-mosquitto mosquitto -c /mosquitto-no-auth.conf
```

If this is my docker-compose.yml file, how do integrate this syntax ```mosquitto -c /mosquitto-no-auth.conf``` to docker-compose.yml file?

**_docker-compose.yml_**
```
version: "3.4"
services:
  mqtt:
     container_name: mosquitto_name
     image: eclipse-mosquitto
     volumes:
       - /home/tmp/mosquitto/data:/mosquitto/data
       - /home/tmp/mosquitto/log:/mosquitto/log
     network_mode: host

```

**Comment by luan-dang-techlabs** [comment]
I figured it out:

```
version: "3.4"
services:
  mqtt:
     container_name: mosquitto_name
     image: eclipse-mosquitto
     volumes:
       - /home/tmp/mosquitto/data:/mosquitto/data
       - /home/tmp/mosquitto/log:/mosquitto/log
     network_mode: host
     command: mosquitto -c /mosquitto-no-auth.conf
```
